name: Generate Dynamic Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git emacs python3-pip pandoc
        sudo pip install xml2rfc

    - name: Prepare Deployment Directory
      run: |
        mkdir -p publish

    - name: Copy results
      run: cp -r tests-trex publish/

    - name: "Convert README.org to index.html"
      run: |
        pandoc pages/README.org --from=org --to=html5 \
          --standalone --toc  --self-contained \
          --resource-path=".:pages:results" \
          -o publish/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: publish
        publish_branch: gh-pages
        keep_files: true
        cname: ''
        allow_empty_commit: false
